# Generated by Django 4.1.2 on 2022-11-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0003_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('camada', models.IntegerField()),
            ],
        ),
    ]
