# Generated by Django 4.1.2 on 2022-11-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0004_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
